-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MY_STORE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MY_STORE` DEFAULT CHARACTER SET utf8 ;

USE `MY_STORE` ;


-- -----------------------------------------------------
-- Table `MY_STORE`.`CUSTOMERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`CUSTOMERS` (
  `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PHONE` INT(10) NOT NULL,
  `ADDRESS` TINYTEXT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
  UNIQUE INDEX `PHONE_UNIQUE` (`PHONE` ASC),
  INDEX IDX_CUSTOMERS_NAME (NAME)
  )
ENGINE = InnoDB;


CREATE TABLE COLOUR (
    COLOUR_ID INT AUTO_INCREMENT PRIMARY KEY,
    COLOUR_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE BRAND (
    BRAND_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SIZE (
    SIZE_ID INT AUTO_INCREMENT PRIMARY KEY,
    SIZE_LABEL VARCHAR(20) NOT NULL
);

CREATE TABLE MATERIAL (
    MATERIAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    MATERIAL_NAME VARCHAR(100) NOT NULL
);


-- -----------------------------------------------------
-- Table `MY_STORE`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`PRODUCTS` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `PRICE` DECIMAL(10, 2) NOT NULL,
  `DESCRIPTION` TINYTEXT NULL,
  `STOCK_LEVEL` INT NOT NULL,
  `GENDER` ENUM('Men', 'Women', 'Unisex') NOT NULL,
  `BRAND_ID` INT NOT NULL,
  `CATEGORY_ID` INT NOT NULL,
  `MATERIAL_ID` INT NOT NULL,

  PRIMARY KEY (`PRODUCT_ID`),

  CONSTRAINT `FK_PRODUCTS_BRAND`
    FOREIGN KEY (`BRAND_ID`)
    REFERENCES `MY_STORE`.`BRAND` (`BRAND_ID`),

  CONSTRAINT `FK_PRODUCTS_CATEGORY`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `MY_STORE`.`CATEGORY` (`CATEGORY_ID`),

  CONSTRAINT `FK_PRODUCTS_MATERIAL`
    FOREIGN KEY (`MATERIAL_ID`)
    REFERENCES `MY_STORE`.`MATERIAL` (`MATERIAL_ID`),

  INDEX `IDX_PRODUCTS_NAME` (`NAME`),
  INDEX `IDX_PRODUCTS_CATEGORY` (`CATEGORY_ID`),
  INDEX `IDX_PRODUCTS_BRAND` (`BRAND_ID`),
  INDEX `IDX_PRODUCTS_GENDER` (`GENDER`)
)
ENGINE = InnoDB;



-- Create many-to-many relationships

-- Product_Color table with surrogate primary key
CREATE TABLE PRODUCT_COLOUR (
    PRODUCT_COLOUR_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    COLOUR_ID INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (COLOUR_ID) REFERENCES COLOUR(COLOUR_ID)
);

-- Product_Size table with surrogate primary key
CREATE TABLE PRODUCT_SIZE (
    PRODUCT_SIZE_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    SIZE_ID INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (SIZE_ID) REFERENCES SIZE(SIZE_ID)
);


-- -----------------------------------------------------
-- Table `MY_STORE`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`ORDERS` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `ORDER_DATE` DATETIME NOT NULL,
  `TOTAL_AMOUNT` INT NOT NULL,
  `ORDER_STATUS` SET('Pending', 'Shipped', 'Delivered', 'Cancelled') NOT NULL,
  `PAYMENT_STATUS` SET('Pending', 'Completed', 'Failed', 'Refunded') NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  INDEX `IDX_ORDERS_CUSTOMER_ID` (`CUSTOMER_ID` ASC),
  INDEX `IDX_ORDERS_ORDER_DATE` (`ORDER_DATE` DESC),
  CONSTRAINT `FK_ORDERS_CUSTOMERS`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `MY_STORE`.`CUSTOMERS` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS BAG (
    BAG_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL UNIQUE,
    CONSTRAINT `FK_BAG_CUSTOMERS`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `MY_STORE`.`CUSTOMERS` (`CUSTOMER_ID`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS BAG_PRODUCT (
    BAG_PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    BAG_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT DEFAULT 1,
    UNIQUE (BAG_ID, PRODUCT_ID),
    CONSTRAINT `FK_BAG_PRODUCT_BAG`
        FOREIGN KEY (BAG_ID) REFERENCES BAG(BAG_ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `FK_BAG_PRODUCT_PRODUCTS`
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
            ON DELETE CASCADE
            ON UPDATE CASCADE
);


-- -----------------------------------------------------
-- Table `MY_STORE`.`ORDER_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`ORDER_DETAILS` (
  `ORDER_DETAILS_ID` INT NOT NULL AUTO_INCREMENT,
  `QUANTITY` INT NOT NULL,
  `PRICE_AT_PURCHASE` DECIMAL(10, 2) NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `ORDER_ID` INT NOT NULL,

  PRIMARY KEY (`ORDER_DETAILS_ID`),
  
  INDEX `IDX_ORDER_DETAILS_PRODUCT_ID` (`PRODUCT_ID` ASC),

  CONSTRAINT `FK_ORDER_DETAILS_ORDER`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `MY_STORE`.`ORDERS` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `FK_ORDER_DETAILS_PRODUCT`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `MY_STORE`.`PRODUCTS` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- Recommendation Engine Table

-- -----------------------------------------------------
-- Table `MY_STORE`.`PRODUCT_ASSOCIATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`PRODUCT_ASSOCIATION` (
    `ASSOCIATION_ID` INT AUTO_INCREMENT PRIMARY KEY,
    `PRODUCT_ID` INT NOT NULL,
    `ASSOCIATED_PRODUCT_ID` INT NOT NULL,
    `FREQUENCY` INT DEFAULT 1,

    CONSTRAINT `FK_PRODUCT_ASSOCIATION_PRODUCT`
      FOREIGN KEY (`PRODUCT_ID`) 
      REFERENCES `MY_STORE`.`PRODUCTS` (`PRODUCT_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,

    CONSTRAINT `FK_PRODUCT_ASSOCIATION_ASSOCIATED`
      FOREIGN KEY (`ASSOCIATED_PRODUCT_ID`) 
      REFERENCES `MY_STORE`.`PRODUCTS` (`PRODUCT_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,

    UNIQUE (`PRODUCT_ID`, `ASSOCIATED_PRODUCT_ID`),

    INDEX `IDX_PRODUCT_ASSOCIATION_FREQUENCY` (`FREQUENCY`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MY_STORE`.`RETURNS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`RETURNS` (
  `RETURN_ID` INT NOT NULL AUTO_INCREMENT,
  `RETURN_REASON` VARCHAR(100) NOT NULL,
  `RETURN_STATUS` SET('Pending', 'Processing', 'Completed', 'Rejected') NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `ORDER_DETAIL_ID` INT NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  `ORDER_ID` INT NOT NULL,
  
  PRIMARY KEY (`RETURN_ID`),
  
  INDEX `IDX_RETURNS_PRODUCT` (`PRODUCT_ID`),
  INDEX `IDX_RETURNS_CUSTOMER` (`CUSTOMER_ID`),
  INDEX `IDX_RETURNS_ORDER` (`ORDER_ID`),
  INDEX `IDX_RETURNS_ORDER_DETAIL` (`ORDER_DETAIL_ID`),
  
  CONSTRAINT `FK_RETURNS_PRODUCT`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `MY_STORE`.`PRODUCTS` (`PRODUCT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
  CONSTRAINT `FK_RETURNS_CUSTOMER`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `MY_STORE`.`CUSTOMERS` (`CUSTOMER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
  CONSTRAINT `FK_RETURNS_ORDER`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `MY_STORE`.`ORDERS` (`ORDER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    
  CONSTRAINT `FK_RETURNS_ORDER_DETAIL`
    FOREIGN KEY (`ORDER_DETAIL_ID`)
    REFERENCES `MY_STORE`.`ORDER_DETAILS` (`ORDER_DETAILS_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MY_STORE`.`RECOMMENDATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`RECOMMENDATIONS` (
  `RECOMMENDATION_ID` INT NOT NULL AUTO_INCREMENT,
  `RECOMMENDATION_DATE` DATETIME NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `ORDER_DETAIL_ID` INT NOT NULL,
  `CUSTOMER_ID` INT NOT NULL,
  
  PRIMARY KEY (`RECOMMENDATION_ID`),
  
  INDEX `IDX_RECOMMENDATIONS_PRODUCT` (`PRODUCT_ID`),
  INDEX `IDX_RECOMMENDATIONS_ORDER_DETAIL` (`ORDER_DETAIL_ID`),
  INDEX `IDX_RECOMMENDATIONS_CUSTOMER` (`CUSTOMER_ID`),
  
  CONSTRAINT `FK_RECOMMENDATIONS_PRODUCT`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `MY_STORE`.`PRODUCTS` (`PRODUCT_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  
  CONSTRAINT `FK_RECOMMENDATIONS_ORDER_DETAIL`
    FOREIGN KEY (`ORDER_DETAIL_ID`)
    REFERENCES `MY_STORE`.`ORDER_DETAILS` (`ORDER_DETAILS_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT `FK_RECOMMENDATIONS_CUSTOMER`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `MY_STORE`.`CUSTOMERS` (`CUSTOMER_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MY_STORE`.`STOCK_UPDATES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MY_STORE`.`STOCK_UPDATES` (
  `STOCK_UPDATE_ID` INT NOT NULL AUTO_INCREMENT,
  `UPDATED_STOCK_LEVEL` INT NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  
  PRIMARY KEY (`STOCK_UPDATE_ID`),
  
  CONSTRAINT `FK_STOCK_UPDATES_PRODUCT`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `MY_STORE`.`PRODUCTS` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  INDEX `IDX_PRODUCT_UPDATE_DATE` (`PRODUCT_ID`, `UPDATE_DATE`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
